name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.2'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r test_requirements.txt
      - name: Test with pytest
        run: |
           pytest --html=test-report.html --cov-report=html:test-report-cov --cov=turn_the_page_bot
      - name: Upload pytest results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: test-report.html
      - name: Upload pytest cov results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: test-report-cov/
